import { extendTheme, withDefaultColorScheme } from '@chakra-ui/react'
import { withFocusVisible, withBodyColorMode } from '@v1v2/chakra'

export const primaryColor = '#6C29D6'

const theme = extendTheme(
  withFocusVisible(),
  withBodyColorMode({ background: ['white', 'purple.900'], color: ['gray.700', 'purple.50'] }),
  withDefaultColorScheme({ colorScheme: 'purple' }),
  {
    colors: {
      purple: {
        // Generated by https://themera.vercel.app
        '50': '#F0EAFB',
        '100': '#D6C3F4',
        '200': '#BB9DEC',
        '300': '#A176E5',
        '400': '#8650DD',
        '500': primaryColor,
        '600': '#5621AB',
        '700': '#411980',
        '800': '#2B1056',
        '900': '#16082B',
      },
    },
  }
)

export default theme
